# Step2_emotions

--------------------------------------
The goal of this script is to perform sentiment and keywords analysis on the Theatre's Reviews

## I) Load Libraries

In [1]:
import pandas as pd
import numpy as np
from textblob import TextBlob
import text2emotion as te
import nltk
from gensim.summarization import keywords
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

## II) Load Data

In [2]:
df = pd.read_excel("corpus_I_2clustering.xlsx")
display(df.head(3))
display(df.shape)

                Corpus   Newspaper / Blog Date of Publication            Reviewer     Sex       Title of the Play        Playwright Rating                                             Review              Theatre  Women/Feminism  LGBT / Queer / Sexuality / Gender  Disabled  Politics  Supernatural  Science  Body  Childhood  Cultural difference / Race  Death  Education  Family  Environment  Friendship  Love  Identity  Memory  Relationships  Religion  Violence  Spectator_Cat  Audience_Cat  Show_Cat  Story_Cat  Decor_Cat  Theatre_Cat  Production_Cat  Character_Cat  End_Cat  Beginning_Cat  Max_Value      Cluster
0  Corpus I (Journalism)         Guardian          07.01.2010  Michael Billington    Male  THE LADY OR THE TIGER   Michael Richmond   None  Sam Walters clearly has a soft spot for this t...  Orange Tree Theatre               2                                  1         0         1             1        0     0          1                           0      1          0       1            0           2     2         0       0              0         0         0              0             1         2          1          0            3               0              0        1              2          3  Theatre_Cat
1  Corpus I (Journalism)  Daily Telegraph          07.01.2010     Charles Spencer    Male  THE LADY OR THE TIGER   Michael Richmond   None  Unbelievably, The Lady or the Tiger is one of ...  Orange Tree Theatre               2                                  1         0         0             0        0     1          3                           1      2          0       1            0           1     1         0       0              0         0         0              1             2         4          0          0            1               1              0        3              0          4     Show_Cat
2  Corpus I (Journalism)  Financial Times          08.01.2010       Sarah Hemming  Female  THE LADY OR THE TIGER   Michael Richmond   None  Party political leaders in search of eye-catch...  Orange Tree Theatre               1                                  0         0         1             1        0     3          0                           0      1          1       0            0           0     0         0       0              0         0         0              1             1         5          3          0            1               1              1        1              1          5     Show_Cat

(21806, 42)

## III) Sentiment Analysis

In [3]:
sid = SentimentIntensityAnalyzer()

In [12]:
df2 = df.copy()
list_neg = []
list_neu = []
list_pos = []
list_compound = []
list_polarity = []
list_subjectivity = []
for i in range(0,len(df2["Review"])):
    score1 = sid.polarity_scores(df2["Review"][i])
    score2 = TextBlob(df2["Review"][i]).sentiment
    list_neg.append(score1['neg'])
    list_neu.append(score1['neu'])
    list_pos.append(score1['pos'])
    list_compound.append(score1['compound'])
    list_polarity.append(score2[0])
    list_subjectivity.append(score2[1])

In [13]:
df2["Neg"] = list_neg
df2["Neu"] = list_neu
df2["Pos"] = list_pos
df2["Compound"] = list_compound
df2["Polarity"] = list_polarity
df2["Subjectivity"] = list_subjectivity

In [14]:
display(df2.head(3))
display(df2.shape)

                Corpus   Newspaper / Blog Date of Publication            Reviewer     Sex       Title of the Play        Playwright Rating                                             Review              Theatre  Women/Feminism  LGBT / Queer / Sexuality / Gender  Disabled  Politics  Supernatural  Science  Body  Childhood  Cultural difference / Race  Death  Education  Family  Environment  Friendship  Love  Identity  Memory  Relationships  Religion  Violence  Spectator_Cat  Audience_Cat  Show_Cat  Story_Cat  Decor_Cat  Theatre_Cat  Production_Cat  Character_Cat  End_Cat  Beginning_Cat  Max_Value      Cluster    Neg    Neu    Pos  Compound  Polarity  Subjectivity
0  Corpus I (Journalism)         Guardian          07.01.2010  Michael Billington    Male  THE LADY OR THE TIGER   Michael Richmond   None  Sam Walters clearly has a soft spot for this t...  Orange Tree Theatre               2                                  1         0         1             1        0     0          1                           0      1          0       1            0           2     2         0       0              0         0         0              0             1         2          1          0            3               0              0        1              2          3  Theatre_Cat  0.060  0.828  0.111    0.9646  0.037865      0.386999
1  Corpus I (Journalism)  Daily Telegraph          07.01.2010     Charles Spencer    Male  THE LADY OR THE TIGER   Michael Richmond   None  Unbelievably, The Lady or the Tiger is one of ...  Orange Tree Theatre               2                                  1         0         0             0        0     1          3                           1      2          0       1            0           1     1         0       0              0         0         0              1             2         4          0          0            1               1              0        3              0          4     Show_Cat  0.118  0.789  0.093   -0.9676  0.021624      0.542852
2  Corpus I (Journalism)  Financial Times          08.01.2010       Sarah Hemming  Female  THE LADY OR THE TIGER   Michael Richmond   None  Party political leaders in search of eye-catch...  Orange Tree Theatre               1                                  0         0         1             1        0     3          0                           0      1          1       0            0           0     0         0       0              0         0         0              1             1         5          3          0            1               1              1        1              1          5     Show_Cat  0.052  0.818  0.130    0.9844  0.026978      0.482566

(21806, 48)

In [5]:
df_corpus_v3 = df2
df_corpus_v3["Emotion"] = ""
df_corpus_v3["Emotion"][0:5] = df_corpus_v3["Review"][0:5].apply(lambda x:te.get_emotion(x))

In [2]:
list_emotion_angry = []
list_emotion_fear = []
list_emotion_happy = []
list_emotion_sad = []
list_emotion_surprise = []
for i in range(0,len(df_corpus_v3["Review"])):
  print(i)
  emotion =te.get_emotion(df_corpus_v3["Review"][i])
  list_emotion_angry.append(emotion["Angry"])
  list_emotion_fear.append(emotion["Fear"])
  list_emotion_happy.append(emotion["Happy"])
  list_emotion_sad.append(emotion["Sad"])
  list_emotion_surprise.append(emotion["Surprise"])

In [24]:
df_corpus_v3["Angry"] = list_emotion_angry
df_corpus_v3["Fear"] = list_emotion_fear
df_corpus_v3["Happy"] = list_emotion_happy
df_corpus_v3["Sad"] = list_emotion_sad
df_corpus_v3["Surpise"] = list_emotion_surprise

In [25]:
df_corpus_v3.to_excel("corpus_I_2clustering_emotions.xlsx")

In [55]:
df3 = df2.copy()
df3.head(3)

,index,Newspaper,Date,Reviewer,Title,Theatre,Rating,Keywords,Review,Lat,Long,Year,Neg,Neu,Pos,Compound,Polarity,Subjectivity
0,0,A YOUNGER THEATER,2020-11-12,Jessica Handscomb,The Dumb Waiter,Hampstead Theatre,4.0,"Alec Newman,Alice Hamilton,Harold Pinter,James...",\nI think it’s fair to say that 2020 has been ...,51.543817,-0.173817,2020.0,0.123,0.776,0.102,-0.9582,0.067633,0.519686
1,1,A YOUNGER THEATER,2020-10-12,Jessica Handscomb,Mr Stink,Chickenshed Theatre,3.0,"Belinda McGuirk,Bethany Hamlin,Bradley Davis,C...",\nDavid Walliams is not my favourite children’...,51.644387,-0.145171,2020.0,0.166,0.715,0.119,-0.9823,0.128100,0.495122
2,2,A YOUNGER THEATER,2020-08-12,Olivia Kiely,The Gruffalo’s Child,Tall Stories,3.0,"Alexandra Palace,Althea Burey,Andy Shaw,Axel S...",\nIt is fair to say that I’m a bit older than ...,51.549105,-0.107475,2020.0,0.043,0.748,0.209,0.9985,0.241531,0.583156

## IV) Keywords Analysis

In [8]:
df_corpus_v4 = df_corpus_v3

In [4]:
list_keywords = []
for i in range(0,len(df_corpus_v4['Review'])):
    print(i)
    text_en = (df_corpus_v4['Review'][i])
    list_keywords.append(keywords(text_en,words = 10,scores = True, lemmatize = True))

In [7]:
df_corpus_v4['Top_10_Keywords'] = list_keywords

In [8]:
df_corpus_v4.head(4)

,Unnamed: 0,Corpus,Newspaper / Blog,Date of Publication,Reviewer,Sex,Title of the Play,Playwright,Rating,Review,...,Compound,Polarity,Subjectivity,Emotion,Angry,Fear,Happy,Sad,Surpise,Top_10_Keywords
0,0,Corpus I (Journalism),Guardian,07.01.2010,Michael Billington,Male,THE LADY OR THE TIGER,Michael Richmond,None,Sam Walters clearly has a soft spot for this t...,...,0.9646,0.037865,0.386999,NaN,0.09,0.36,0.11,0.32,0.13,"[(musical, 0.18205417189782674), (adult, 0.159..."
1,1,Corpus I (Journalism),Daily Telegraph,07.01.2010,Charles Spencer,Male,THE LADY OR THE TIGER,Michael Richmond,None,"Unbelievably, The Lady or the Tiger is one of ...",...,-0.9676,0.021624,0.542852,NaN,0.07,0.40,0.08,0.27,0.18,"[(news, 0.1621906876956508), (script, 0.138598..."
2,2,Corpus I (Journalism),Financial Times,08.01.2010,Sarah Hemming,Female,THE LADY OR THE TIGER,Michael Richmond,None,Party political leaders in search of eye-catch...,...,0.9844,0.026978,0.482566,NaN,0.15,0.37,0.20,0.20,0.10,"[(work, 0.1354778026264658), (little, 0.135477..."
3,3,Corpus I (Journalism),Jewish Chronicle,08.01.2010,John Nathan,Male,THE LADY OR THE TIGER,Michael Richmond,None,Michael Richmond’s and Nola York’s quirky litt...,...,0.9932,0.050972,0.496414,NaN,0.07,0.38,0.12,0.22,0.21,"[(little, 0.2651071590881793), (tiger, 0.15550..."

In [9]:
df_corpus_v4 = df_corpus_v4.loc[:, ~df_corpus_v4.columns.str.contains('^Unnamed')]
df_corpus_v4.head(3)

,Corpus,Newspaper / Blog,Date of Publication,Reviewer,Sex,Title of the Play,Playwright,Rating,Review,Theatre,...,Compound,Polarity,Subjectivity,Emotion,Angry,Fear,Happy,Sad,Surpise,Top_10_Keywords
0,Corpus I (Journalism),Guardian,07.01.2010,Michael Billington,Male,THE LADY OR THE TIGER,Michael Richmond,None,Sam Walters clearly has a soft spot for this t...,Orange Tree Theatre,...,0.9646,0.037865,0.386999,NaN,0.09,0.36,0.11,0.32,0.13,"[(musical, 0.18205417189782674), (adult, 0.159..."
1,Corpus I (Journalism),Daily Telegraph,07.01.2010,Charles Spencer,Male,THE LADY OR THE TIGER,Michael Richmond,None,"Unbelievably, The Lady or the Tiger is one of ...",Orange Tree Theatre,...,-0.9676,0.021624,0.542852,NaN,0.07,0.40,0.08,0.27,0.18,"[(news, 0.1621906876956508), (script, 0.138598..."
2,Corpus I (Journalism),Financial Times,08.01.2010,Sarah Hemming,Female,THE LADY OR THE TIGER,Michael Richmond,None,Party political leaders in search of eye-catch...,Orange Tree Theatre,...,0.9844,0.026978,0.482566,NaN,0.15,0.37,0.20,0.20,0.10,"[(work, 0.1354778026264658), (little, 0.135477..."

In [10]:
df_corpus_v4.to_excel("corpus_I_clustering_emotions_v2.xlsx",index=False)

### Great Jobs ✅